# Generated by Django 4.2.10 on 2024-05-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('internal', 'internal User')], max_length=10),
        ),
    ]
