# Generated by Django 5.0.4 on 2024-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("manager", "manager"),
                    ("internal User", "internal User"),
                ],
                max_length=100,
            ),
        ),
    ]
